from text import Text as text
from design import Design as design

class Core:
    def __init__(self) -> str: ...

    '''Logic handling of malrowe goes here, encryption and more can be founded here.'''
    def encrypt_menu(self) -> str: ...

    '''Menu handling section goes here, manipulation of options will be founded here.'''
    def show_menu(self, options: dict) -> dict: ...
    
    def show_banner(self) -> str: ...
    
    def show_info(self) -> str: ...
    
    def read_option(self, options: dict) -> any: ...
    
    def execute_options(self, option: any, options: dict) -> any: ...
    
    def generate_menu(self, options: any, output: any) -> str: ...
    
    def exit_menu(self) -> any: ...

    def main_menu(self) -> str: ...

    def initialize(self) -> any: ...